name: course
channels:
  - conda-forge
dependencies:
  - cmasher
  - jupyter
  - lxml
  - pandas
  - pillow
  - pyarrow
  - requests
  - scipy
  - seaborn
  - sphinx
  - sphinx-gallery
  - sphinx_rtd_theme
  - matplotlib
  - numpy
  - scikit-learn
  - linkify-it-py
  - pip
  - xgboost
  - pyreadstat
  - termcolor
  - time
  - pip:
      - adjustText
      - highlight-text
      - kloppy
      - mplsoccer
      - sphinxcontrib-youtube
      - myst-parser
